# -*- coding: utf-8 -*-
"""random forest project 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iP8h0SeY0wxOZ9PAuUKQN-zDMP6IWu7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as  plt

from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_csv("/content/drive/MyDrive/Social_Network_Ads (1).csv")
print(dataset.head())

x = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, 4].values

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
x[:, 0] = le.fit_transform(x[:, 0])

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.25, random_state=0
)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print(y_pred)

import matplotlib.pyplot as plt

plt.scatter(x_train[:, 0], x_train[:, 1], c=y_train)
plt.title("Random Forest - Test Set")
plt.xlabel("Age")
plt.ylabel("Salary")
plt.show()

plt.scatter(x_test[:, 0], x_test[:, 1], c=y_test)
plt.title("Random Forest - Test Set")
plt.xlabel("Age")
plt.ylabel("Salary")
plt.show()