# -*- coding: utf-8 -*-
"""titanic rf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHyeivC0IVUwYa2RCjXLGmssHnilTAMp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset  = pd.read_csv("/content/drive/MyDrive/Titanic-Dataset (1).csv")
print(dataset.head())

dataset = dataset [["Pclass","Sex","Age","Fare","Survived"] ]
dataset = dataset.dropna()

x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, 4].values

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
x[:,1] = le.fit_transform(x[:,1])

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
 x, y, test_size = 0.2, random_state =0
 )

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=10, random_state=0)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

plt.scatter(x_train[:,0], x_train[:,1], c=y_train)
plt.title("Training Set")
plt.xlabel("Age")
plt.ylabel("Fare")
plt.show()

plt.scatter(x_test[:,0], x_test[:,1], c=y_test)
plt.title("Test Set")
plt.xlabel("Age")
plt.ylabel("Fare")
plt.show()